CREATE TABLE LEDGER (
	ENTRY_NO INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
, ENTRY_TYPE TEXT NOT NULL, ENTRY_CATEGORY TEXT NOT NULL, ENTRY_VALUE NUMERIC NOT NULL, ENTRY_DATE INTEGER NOT NULL, MODE_OF_TRAN TEXT, EXTERNAL_TRAN_ID INTEGER, PAN_NO TEXT);


CREATE TABLE "MEMBER" (
	MEMBER_NO INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	NICK_NAME TEXT, 
	ADDRESS TEXT,
	MEMBERSHIP_TYPE TEXT
, MOBILE_NO TEXT,
PHONE_NO TEXT, EMAIL TEXT, DATE_OF_BIRTH INTEGER, LEDGE_ENTRY_NO INTEGER NOT NULL);


CREATE TABLE DONATION (
	DONATION_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	LEDGE_ENTRY_NO INTEGER NOT NULL,
	NAME TEXT NOT NULL,
	NICK_NAME TEXT,
	ADDRESS TEXT,
	MOBILE_NO TEXT,
	PHONE_NO TEXT,
	EMAIL TEXT,
	DATE_OF_BIRTH INTEGER
);


CREATE TABLE INVENTORY (
	INVENTORY_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	LEDGER_ENTRY_NO INTEGER NOT NULL,
	INVENTRY_TYPE TEXT NOT NULL,
	INVENTROY_COUNT INTEGER NOT NULL
);
